### ISSUE TITLE
我按照您的教程设置了windowed和分辨率 但是使用maiDXR启动游戏后无法显示整个maimai的画面 

### ISSUE THREAD

**Issue by a16239438** [xiaopeng12138/MaiDXR#10]

**Comment by xiaopeng12138** [comment]
首先，我没在法国论坛发过教程。其次，你的游戏要处在电脑屏幕里面才可以捕捉，并且必须得是无修改版本2p的游戏本体。如果你的画面和 #7 的情况一样，那么就是设置错误

**Comment by a16239438** [comment]
根据您的反馈，我已经解决了问题，感谢回复

**Comment by a16239438** [comment]
另一个问题是，相比于B站看到的视频而言，我在游戏过程中感觉游戏画面有些许晃动，这个问题您知道是怎么回事吗 我的设备是 quest2 采用VD串流

**Comment by xiaopeng12138** [comment]
> 另一个问题是，相比于B站看到的视频而言，我在游戏过程中感觉游戏画面有些许晃动，这个问题您知道是怎么回事吗 我的设备是 quest2 采用VD串流

如果不在游玩中移动视角没问题，仅在游戏中有问题的话，是正常的。可能是因为系统性能占用太多导致的跟不上，或者就是因为游玩过程中太抖了。vd的延迟可能会加剧抖动，如果换成link（有线）还是有问题那就没什么办法了

**Comment by a16239438** [comment]
我在指定目录放入20位数字后 aime卡并不工作 每次都只能以游客模式游玩

**Comment by xiaopeng12138** [comment]
> 我在指定目录放入20位数字后 aime卡并不工作 每次都只能以游客模式游玩

本repo不讨论本体问题，看上去你的问题解决了，我就关issue了
