### ISSUE TITLE
能否添加test与serve按键映射到游戏

### ISSUE THREAD

**Issue by FeiZhaixiage** [xiaopeng12138/MaiDXR#11]
因为我的游戏无法保存设定信息 所以我每一次都要在键盘上对游戏进行操作。
希望能够在机器右下方加入test与serve按键。
我认为在Settings.json中能够配置这些映射的按键是一个好的主意，不只是test与serve按键，希望其他按键也能够进行映射。
如果可以的话辛苦您了。

**Comment by xiaopeng12138** [comment]
会在下个版本中考虑加入

**Comment by FeiZhaixiage** [comment]
> 会在下个版本中考虑加入

感谢 辛苦您了

**Comment by xiaopeng12138** [comment]
v0.6已经加入4个自定义按钮
