### ISSUE TITLE
crash after unity logo

### ISSUE THREAD

**Issue by xiaopeng12138** [xiaopeng12138/MaiDXR#14]
It looks like many people have this problem. Idk what causes it. Maybe it's because of GPU. But I can't recreate it in my laptop. 
Possible problem:
- wrong player setting
- wrong graphic settings
- openxr issue
- serial issue
if you have same problem, pls sent your PC specs here (CPU, GPU, Windows Version, Headset model)

**Comment by fkiliver** [comment]
> It looks like many people have this problem. Idk what causes it. Maybe it's because of GPU. But I can't recreate it in my laptop. Possible problem:
> 
> * wrong player setting
> * wrong graphic settings
> * openxr issue
> * serial issue
>   if you have same problem, pls sent your PC specs here (CPU, GPU, Windows Version, Headset model)

I have the same problem, but I found a solution
1. If you start sinmai first and then maidxr, you need to close the port binding and open the port mapping after maidxr enters the game
2. (recommended) start maidxr first, and then it usually gets stuck. Then start sinmai, and maidxr will automatically return to normal
When I run the project in the unit editor, the editor will always report an error that cannot link the port. I speculate that the process is blocked due to the failure of port communication

**Comment by xiaopeng12138** [comment]
> > It looks like many people have this problem. Idk what causes it. Maybe it's because of GPU. But I can't recreate it in my laptop. Possible problem:
> > 
> > * wrong player setting
> > * wrong graphic settings
> > * openxr issue
> > * serial issue
> >   if you have same problem, pls sent your PC specs here (CPU, GPU, Windows Version, Headset model)
> 
> I have the same problem, but I found a solution
> 
> 1. If you start sinmai first and then maidxr, you need to close the port binding and open the port mapping after maidxr enters the game
> 2. (recommended) start maidxr first, and then it usually gets stuck. Then start sinmai, and maidxr will automatically return to normal
>    When I run the project in the unit editor, the editor will always report an error that cannot link the port. I speculate that the process is blocked due to the failure of port communication

Thank you for the solution. I think I know what is the issue. Can you try enable buffers in com2com and see if the problem is still Herren or not. If it still crash, i will rewrite all serial code.

**Comment by xiaopeng12138** [comment]
Ok, I found the issue, You must enable the enable buffer option in com2com on both ports of all pairs. Otherwise, your MaiDXR will crash after the Unity logo.
