### ISSUE TITLE
没反应

### ISSUE THREAD

**Issue by mkdls** [xiaopeng12138/MaiDXR#15]
圆圈的八个键有震动但不能互动

**Comment by mkdls** [comment]
输入法是用英文的，但按键要怎么改

**Comment by xiaopeng12138** [comment]
> 输入法是用英文的，但按键要怎么改

目前改不了MaiDXR输出的按键，只能修改游戏的按键，这具体我就不知道了，不过如果tools是正常的话理论上都是那几个按键的：xcdewqaz（从最下面左手开始）

**Comment by mkdls** [comment]
好谢谢

**Comment by mkdls** [comment]
那要怎么才能修复

**Comment by mkdls** [comment]
Tools是segatools吗

**Comment by xiaopeng12138** [comment]
> Tools是segatools吗

这不是不明说都知道的吗，我不知道你哪里获得的，这类问题找源头吧，如果MaiDXR输出按键正常那就不是我的问题了

**Comment by mkdls** [comment]
好
