### ISSUE TITLE
能否加个锁定其他功能按键的功能

### ISSUE THREAD

**Issue by DSRLIN** [xiaopeng12138/MaiDXR#17]
感觉经常性的会在打歌的时候穿模甩到刷卡键或者Test键上wwwwww

**Comment by xiaopeng12138** [comment]
草，你是多用力，刷卡应该不影响，test可以改设置到最下面那个按钮，按钮锁定太反直觉了，应该不会加，看情况把

**Comment by DSRLIN** [comment]
主要是刷卡会导致游戏直接暂停 然后恢复就基本上没分数了www 就这样吧

**Comment by xiaopeng12138** [comment]
草，原来暂停是因为刷卡，可能会加个双手同时按下确认

**Comment by xiaopeng12138** [comment]
在v0.8中加入
