### ISSUE TITLE
本地编译需要什么环境包

### ISSUE THREAD

**Issue by SaltyFishOnTheSea** [xiaopeng12138/MaiDXR#18]
RT，这个需要在什么环境下才能编译

**Comment by xiaopeng12138** [comment]
readme里面写了unity官方软件包以外需要安装的包和dll，一个是[uWindowCapture](https://github.com/hecomi/uWindowCapture)，另一个是[InputSimulator](https://www.nuget.org/packages/InputSimulator)，只用了里面的一个virtual key code的enum，剩下的理论上都会自动装上去

**Comment by xiaopeng12138** [comment]
如果你要离线编译的话，这里有更详细的要求[packages-lock.json](https://github.com/xiaopeng12138/MaiDXR/tree/main/Packages/packages-lock.json)
当前的Unity版本是2020.3.30f1，然后就标准的unity build support for windows就好了

**Comment by SaltyFishOnTheSea** [comment]
> 如果你要离线编译的话，这里有更详细的要求[packages-lock.json](https://github.com/xiaopeng12138/MaiDXR/tree/main/Packages/packages-lock.json) 当前的Unity版本是2020.3.30f1，装标准的unity build support for windows就好了

非常感谢
