### ISSUE TITLE
按键无效，com口设置也是对的

### ISSUE THREAD

**Issue by y547153** [xiaopeng12138/MaiDXR#19]

**Comment by xiaopeng12138** [comment]
切英文输入法，选择maimai的窗口
然后触屏有效还是都不行

**Comment by xiaopeng12138** [comment]
> 我的也是 com和xxx.ini设置是正确的 也是外键无效 但是内屏可以 外键包括刷卡和test都无效
>  但是我用浏览器搜索框测试vr里的外键却能输出zxcde外键对应的键盘预设 刷卡键也能出发enter指令 但是放在vr里就没反应 
> 输入法是eng 
> 也点开了sinm窗口 
> 之前用的sgtool进游戏了键盘按不了但是vr里的test却可以用  之前com设置成 com5=com3 vr里test居然有反应
>  然后换了一个sgt之后电脑键盘可以用了 但是就像这段反馈开头那样外键不行 com也改回了com3=com5
> 还有一个现象就是刷卡键在vr里有时候有用 有时候没用 
> 我大概遇到的问题就这些了  readme和ini都检查过很多次了 
> 系统win10 21H2 显卡950m
> hdd版本汽水+
> 还需要提供什么吗
> 

如果使用了管理员启动了游戏本体，是会出现一些问题的。不建议使用管理员启动，我不确定用管理员启动maidxr会不会有帮助

**Comment by RuoRanLL** [comment]
> 
这样 谢谢啦

**Comment by xiaopeng12138** [comment]
> 
> COM和ini设置正确，外键无效触屏有效
> 在test里面入力的按钮都是有效的，甚至test界面还能使用下面两个按键设置
> 没开输入法，没用管理员启动
> 同汽水+
> 
> 

你的maidxr什么版本的，然后在游玩的时候使用键盘操控有效吗，如果无效那就不是maidxr的问题了，可以用记事本看看maidxr有没有按键输出，周围一圈按钮是模拟键盘的方式的

**Comment by y547153** [comment]
> 

dxr里没反应，键盘按键的时候屏幕有提示但是不进游戏

**Comment by xiaopeng12138** [comment]
> > 
> 
> dxr里没反应，键盘按键的时候屏幕有提示但是不进游戏

DXR没反应？屏幕白屏？你不用MaiDXR可以进游戏吗。如果你没有用MaiDXR，单纯用键盘的zxcdewqa键也进不了游戏那就不是我的问题了，请自行解决。MaiDXR必须在游戏本体可以运作的情况下运行。（如果要测试键盘是否可用，请把DummyTouch改成1后测试）

**Comment by xiaopeng12138** [comment]
> > 
> 
> dxr里没反应，键盘按键的时候屏幕有提示但是不进游戏

请尝试最新版的MaiDXR

**Comment by xiaopeng12138** [comment]
由于太久没回复，我将关闭这个问题，如果有任何问题，请重新打开
