### ISSUE TITLE
能否加入移动和调整高度功能

### ISSUE THREAD

**Issue by fkiliver** [xiaopeng12138/MaiDXR#2]
这样可以方便地坐在椅子上打mai

**Comment by xiaopeng12138** [comment]
如果是用Oculus Link的话可以暂时使用重置游戏视野功能重置视角，高度似乎因为unity xr工具的关系也会被重置。
未来会加入更方便的调整位置的功能，这个issue我就先开着了

**Comment by xiaopeng12138** [comment]
在 v0.5版本中加入

**Comment by axer0910** [comment]
调整PlayerHigh貌似没有效果

**Comment by xiaopeng12138** [comment]
> 

确实，所以我会再打开这个issue直到修复

**Comment by xiaopeng12138** [comment]
在v0.8中加入
