### ISSUE TITLE
按键有效，触摸无效。。。

### ISSUE THREAD

**Issue by EsCyan** [xiaopeng12138/MaiDXR#20]
Dummytouchpannel改成0和1还有删掉这行都是试过。。。屏幕没反应..

uWindowCapture.log内容为：
[uWC::Err][2022-04-18 01:12:18] WindowsGraphicsCapture::CreateItem() threw an WinRT exception: 0x80070057 参数错误。

**Comment by xiaopeng12138** [comment]
请检查com0com的设置以及com占用

**Comment by xiaopeng12138** [comment]
最好截图setup的设置，如果设置没问题并且你是后开的maidxr，请进入测试模式然后退出测试模式，不然游戏本体的触摸自检会bad

**Comment by EsCyan** [comment]
> 
谢谢，解决了。。跟蓝牙驱动冲突。。。虽然把蓝牙的com换到com7、8去了且com各种设置都正常。。但只要把蓝牙驱动装上，进游戏就触屏失效。。最后找了个老板的蓝牙驱动就好了。。。

**Comment by xiaopeng12138** [comment]
> 同問題，但卸載驅動後仍無效，請問樓主有更詳細的解決辦法嗎

请确保串口绑定正确，新版必须绑定com21和com51，com4和6也尽量绑上去。然后检查mai2.ini的dummytouch的值是否为0。

**Comment by igen0101z** [comment]
已經解決了，先刪藍牙驅動再重裝com0com就成功了
