### ISSUE TITLE
只有左眼画面

### ISSUE THREAD

**Issue by RERASER** [xiaopeng12138/MaiDXR#24]
使用Quest2+VD串流
打开maidxr后自动进入SteamVR环境
只有左眼能看到maidxr的画面
按下菜单键后，左右眼都能看见SteamVR的菜单，但maidxr还是只有左眼

**Comment by xiaopeng12138** [comment]
版本？

**Comment by RERASER** [comment]
v0.7.3

**Comment by xiaopeng12138** [comment]
> v0.7.3

建议退回0.7.2，0.7.3确实有这个bug
