### ISSUE TITLE
Camera on both eyes is not right

### ISSUE THREAD

**Issue by ProgrammingPleb** [xiaopeng12138/MaiDXR#3]
Hi, I have tried this program and one problem that I experienced is that the left eye and the right eye's camera don't seem to be in the right place. This results in two different views on both eyes, making it very nauseating to play. I'm unsure which eyes are in the wrong position, so I just assumed it was both eyes.  
My Quest 2 is configured with 67.8mm eye distance as what Oculus Link tells me. (equivalent to mode 3 in the lens spacing on the headset)

**Comment by xiaopeng12138** [comment]
can you please try older version? I'm not sure what caused this

**Comment by ProgrammingPleb** [comment]
I've tried v0.1 and v0.3.1. I'm going to try the other two versions and see if the issue persists.

**Comment by xiaopeng12138** [comment]
> I've tried v0.1 and v0.3.1. I'm going to try the other two versions and see if the issue persists.

I updated a new version, maybe you can try it, if it still does not work, try starting with steamvr

**Comment by ProgrammingPleb** [comment]
I've tried out the new version and it works! Thank you very much for the fix.
