### ISSUE TITLE
Specific ver of MaiMai?

### ISSUE THREAD

**Issue by Xrayxout** [xiaopeng12138/MaiDXR#37]
Hey, i was wondering if this only works with a specific version of MaiMai? 
the version i have doesn't seem to work at all and am very curious if only works for a specific version of Mai or i had my version set up wrong or MaiDXR isn't seeing my version of MaiMai?

**Comment by xiaopeng12138** [comment]
it supports first dx version and above

**Comment by Xrayxout** [comment]
Ah, so it was my version. my bad. appreciate the quick response tho :)
