### ISSUE TITLE
少了个select按钮

### ISSUE THREAD

**Issue by GEEKiDoS** [xiaopeng12138/MaiDXR#4]
+自己下载修改后启动会卡住 是不是少传了什么东西(指代码）

**Comment by xiaopeng12138** [comment]
阿勒，可能我的git ignore ignore错了？select按钮准备加的，就是好像不是每个人的select按键都一样的，我新版会加个数字键3的select

**Comment by xiaopeng12138** [comment]
看了一下，gitignore应该没错的，我用的github官方的unity模板，自己加了个忽略.meta文件的和vscode的

**Comment by GEEKiDoS** [comment]
> 看了一下，gitignore应该没错的，我用的github官方的unity模板，自己加了个忽略.meta文件的和vscode的，git的文件夹就是我整个unity工程文件夹，没其他文件，你要注意unity版本和依赖有没有装好

我昨天晚上试了一下发现是uWindowsCapture的dll没有 我重新下了个unitypackage装了一下就好了

要不顺便刷卡键也加一下（

**Comment by xiaopeng12138** [comment]
> > 看了一下，gitignore应该没错的，我用的github官方的unity模板，自己加了个忽略.meta文件的和vscode的，git的文件夹就是我整个unity工程文件夹，没其他文件，你要注意unity版本和依赖有没有装好
> 
> 我昨天晚上试了一下发现是uWindowCapture的dll没有 我重新下了个unitypackage装了一下就好了
> 
> 要不顺便刷卡键也加一下（

刷卡有了啊，右边的凸起就是啊，我懒得上贴图了

**Comment by xiaopeng12138** [comment]
v0.4更新了select按键，这个issue我就关掉了
