### ISSUE TITLE
Only one eye is visible.

### ISSUE THREAD

**Issue by meru-golang** [xiaopeng12138/MaiDXR#40]
Quest2+VD is used.
When I used the latest v0.8 version, only one eye was displayed.
Using the 0.7.2 version is a workaround, but I would like to see this problem fixed.

Versions released after v0.8 have the same problem.

**Comment by xiaopeng12138** [comment]
https://maidxr.cf/latest try 0.9b12

**Comment by xiaopeng12138** [comment]
and make sure your gpu supports deferred rendering

**Comment by meru-golang** [comment]
I tried it and it fixed it.
Thank you very much.
