### ISSUE TITLE
中間的觸摸屏沒有反應

### ISSUE THREAD

**Issue by seed27425920** [xiaopeng12138/MaiDXR#41]
我下載了 DX UNiVERSE Plus。在VR中，其他按鍵可以正常使用。不幸的是，中間的觸摸屏沒有反應。也修改了ma2.ini 中的Dummytouchpanel=0 也是沒任何反應 不知道那裡出錯了  有解決辦法嗎？非常感謝
![VirtualDesktop Android-20230207-030437](https://user-images.githubusercontent.com/124660561/217172402-5c9e069b-1dab-4a49-bb64-a478455a33d1.jpg)

**Comment by KengHuai** [comment]
我也是DX UNiVERSE Plus，你是怎么解决的这个问题的？
