### ISSUE TITLE
Taiko no Tatsujin

### ISSUE THREAD

**Issue by Deathmaw** [xiaopeng12138/MaiDXR#5]
I know this is for MaiMai but I would love to see something similar for Taiko no Tatsujin, didn't know where else I would even request something like that, standing at a TnT Arcade Machine in VR and playing would be cool and I imagine it would hook into the game similar as this does, we even have an official version of TnT on PC now on the Microsoft Store / Game Pass.

**Comment by xiaopeng12138** [comment]
it's a pretty good idea, but I'm not a taiko player, idk much about taiko things and I don't have a lot interest on taiko, so I won't have many motivation to make it. I'm sorry. Currently i only interest on making waccaVR, but the io is a issue.
