### ISSUE TITLE
【双人联机】能否添加两个vr联机功能

### ISSUE THREAD

**Issue by fkiliver** [xiaopeng12138/MaiDXR#6]
0.5版本添加了p2触屏，那能不能做出双人联机功能呢，玩家从外部导入人物模型（类似vrc）作为外观

**Comment by xiaopeng12138** [comment]
不能（
因为有各种不同的按键hook方式，而且1和2p只能跑在一个机子上面，就算是局域网连接也会有延迟，你要想要远程那就更难了。
延迟算算就知道了，两个玩家都link，20ms延迟，2p需要1p传输画面到机子上面，vd那种收费串流方案都要30ms，我怎么可能写的出来那么低延迟的传输方案，就算写出来了，到第二台机子上面，过一遍link又是+20ms，总共50ms延迟，然后还要把触摸和按键传到1p上面，这又加延迟。
有个办法，基于店内招募联机，但我测不了，因为没有2台电脑进行局域网测试。

**Comment by fkiliver** [comment]
> 不能（ 因为有各种不同的按键hook方式，而且1和2p只能跑在一个机子上面，就算是局域网连接也会有延迟，你要想要远程那就更难了。 延迟算算就知道了，两个玩家都link，20ms延迟，2p需要1p传输画面到机子上面，vd那种收费串流方案都要30ms，我怎么可能写的出来那么低延迟的传输方案，就算写出来了，到第二台机子上面，过一遍link又是+20ms，总共50ms延迟，然后还要把触摸和按键传到1p上面，这又加延迟。 有个办法，基于店内招募联机，但我测不了，因为没有2台电脑进行局域网测试。

店内招募我等我朋友q2到了可以测试一下

**Comment by xiaopeng12138** [comment]
在未来加入第三人称视角后会决定人物模型和开发联机的必要性，我就先关掉这个issue了，以后再打开

**Comment by xiaopeng12138** [comment]
会在未来考虑加入人物模型

**Comment by xiaopeng12138** [comment]
多人联机已经加入，模型问题移动至#31
